export const taskTypes = [
  {
    statusBg: "#f7a59c",
    statusBd: "#F44336",
    btnLabel: "Start",
    key: "incomplete",
    title: "",
    description: "",
    status: "Incomplete",
    deadline: "",
    createdAt: "",
  },
  {
    statusBg: "#F9EF5C",
    statusBd: "#E7D200",
    btnLabel: "Resolve",
    key: "inprogress",
    title: "",
    description: "",
    status: "In-progress",
    deadline: "",
    createdAt: "",
  },
  {
    statusBg: "#62F95C",
    statusBd: "#0C4A09",
    btnLabel: "Reopen",
    key: "completed",
    title: "",
    description: "",
    status: "Completed",
    deadline: "",
    createdAt: "",
  },
];
